<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { api } from '../api/index.js';
const props = defineProps({ id: String });
const data = ref(null); const error = ref(''); const busy = ref(false); let timer;
const progress = computed(() => { const c = data.value?.counts; const n = data.value?.tasks.length || 0; return n ? Math.round(((c.finished + c.failed + c.cancelled) / n) * 100) : 0; });
async function load() { try { data.value = await api.getEvaluation(props.id); } catch (e) { error.value = e.message; } }
async function action(kind) { busy.value = true; try { if (kind === 'start') { if (!confirm('将调用真实模型并产生费用，确定开始？')) return; await api.startEvaluation(props.id); } else if (kind === 'resume') { if (!confirm('将恢复真实模型调用并产生费用，确定继续？')) return; await api.resumeEvaluation(props.id); } else await api.cancelEvaluation(props.id); await load(); } catch (e) { error.value = e.message; } finally { busy.value = false; } }
onMounted(() => { load(); timer = setInterval(load, 3000); }); onBeforeUnmount(() => clearInterval(timer));
</script>
<template><div v-if="data" class="space-y-5"><div class="flex flex-wrap items-start justify-between gap-4"><div><router-link to="/evaluations" class="text-sm text-slate-400 hover:text-white">返回实验列表</router-link><h1 class="mt-2 text-2xl font-bold text-white">{{ data.run.manifest.experiment_id }}</h1><p class="text-sm text-slate-400 font-mono">{{ data.run.id }}</p></div><div class="flex gap-2"><button v-if="data.run.status === 'planned'" @click="action('start')" :disabled="busy" class="px-4 py-2 bg-amber-600 rounded">确认并启动</button><button v-if="['failed','cancelled'].includes(data.run.status)" @click="action('resume')" class="px-4 py-2 bg-amber-600 rounded">恢复</button><button v-if="data.run.status === 'running'" @click="action('cancel')" class="px-4 py-2 bg-red-700 rounded">取消</button></div></div>
<div class="grid grid-cols-2 md:grid-cols-5 gap-3"><div v-for="s in ['planned','running','finished','failed','cancelled']" :key="s" class="border border-slate-700 bg-slate-900 p-3 rounded"><div class="text-xs uppercase text-slate-500">{{ s }}</div><div class="mt-1 text-2xl text-white tabular-nums">{{ data.counts[s] }}</div></div></div>
<div><div class="flex justify-between text-sm text-slate-400 mb-2"><span>总体进度</span><span>{{ progress }}%</span></div><div class="h-2 bg-slate-800 rounded overflow-hidden"><div class="h-full bg-amber-500" :style="{ width: `${progress}%` }"></div></div></div>
<div class="border border-slate-700 rounded overflow-x-auto"><table class="w-full text-sm"><thead class="text-slate-400 border-b border-slate-700"><tr><th class="p-3 text-left">变体</th><th class="p-3 text-left">种子</th><th class="p-3 text-left">轮换</th><th class="p-3 text-left">状态</th><th class="p-3 text-left">失败原因</th></tr></thead><tbody><tr v-for="task in data.tasks" :key="task.id" class="border-b border-slate-800"><td class="p-3">{{ task.variant_id }}</td><td class="p-3 font-mono text-xs">{{ task.seed }}</td><td class="p-3">{{ task.seat_rotation }}</td><td class="p-3">{{ task.status }}</td><td class="p-3 text-red-300 max-w-md truncate">{{ task.failure_reason }}</td></tr></tbody></table></div></div><div v-else class="text-slate-400">{{ error || '加载中…' }}</div></template>
